### ISSUE TITLE
README.MD required

### ISSUE THREAD

**Issue by soulspark666** [louvian/hentai#6]

**Comment by louvian** [comment]
We don't have a plan to continue this repository in the current periods, maybe someone wants to contribute, I would welcome the pull request.

**Comment by soulspark666** [comment]
Can you at least tell me what it does so I can think of contributing to it!

**Comment by louvian** [comment]
Hello @soulspark666,

We have already deployed another repository about hentai doujinshi. If you are interested to join with us, please email me at louvianlyndal@gmail.com.

You can also visit the site here:
http://ddddd664f3a7dlxn.onion/ (Tor Network only)

This site is totally written in PHP. We are now developing hentai doujinshi scraper that aims to fill the site contents. Our scraper is currently working properly and auto updated againts new contents, it runs on background as daemon and exposes its content to the dark web (which can only be accessed via Tor Proxy).

So, here we use:
1. PHP 7.3 (for daemon and web)
2. MySQL 5.6 (database)
3. Nginx (web server)

Our applications are running on Linux. I will invite you to our group chat if you want too. (You could find the group chat link on that site, though).
